In [144]:
import numpy as np
import pandas as pd
import seaborn as sns; sns.set()
import random
# Import library yang dibutuhkan

In [145]:
data = pd.read_csv('./dataset.csv')
data
# Read data dalam bentuk csv

Asal        Tujuan  Jarak  Waktu  KonfirmasiCovid
0      Puskesmas     Puskesmas   0.00      0         0.000000
1      Puskesmas  SerdangWetan   5.20     11         0.000000
2      Puskesmas      Palasari   4.40     16         0.000000
3      Puskesmas     Rancagong   4.10     11         0.000000
4      Puskesmas         Legok   2.30      7         0.000000
5      Puskesmas       Babakan   0.02      1         0.000000
6   SerdangWetan     Puskesmas   5.30     11         0.000000
7   SerdangWetan  SerdangWetan   0.00      0         0.000000
8   SerdangWetan      Palasari   4.70     13         0.497059
9   SerdangWetan     Rancagong   3.20      9         0.864706
10  SerdangWetan         Legok   4.00     10         2.152941
11  SerdangWetan       Babakan   5.30     11         1.082353
12      Palasari     Puskesmas   4.40     16         0.000000
13      Palasari  SerdangWetan   4.70     13         2.011834
14      Palasari      Palasari   0.00      0         0.000000
15      Palasari     Rancagong   4.80     14         1.739645
16      Palasari         Legok   4.20     13         4.331361
17      Palasari       Babakan   2.80     10         2.177515
18     Rancagong     Puskesmas   4.10     11         0.000000
19     Rancagong  SerdangWetan   3.20      9         1.156463
20     Rancagong      Palasari   4.80     14         0.574830
21     Rancagong     Rancagong   0.00      0         0.000000
22     Rancagong         Legok   2.20      8         2.489796
23     Rancagong       Babakan   4.10     11         1.251701
24         Legok     Puskesmas   1.90      7         0.000000
25         Legok  SerdangWetan   4.00      9         0.464481
26         Legok      Palasari   4.20     15         0.230874
27         Legok     Rancagong   2.20      8         0.401639
28         Legok         Legok   0.00      0         0.000000
29         Legok       Babakan   2.30      6         0.502732
30       Babakan     Puskesmas   0.02      1         0.000000
31       Babakan  SerdangWetan   5.30     11         0.923913
32       Babakan      Palasari   2.80     10         0.459239
33       Babakan     Rancagong   4.10     11         0.798913
34       Babakan         Legok   2.00      8         1.989130
35       Babakan       Babakan   0.00      0         0.000000

In [146]:
data.isnull().sum()
# Menghitung jumlah data yang NULL

Asal               0
Tujuan             0
Jarak              0
Waktu              0
KonfirmasiCovid    0
dtype: int64

In [147]:
jarak = np.zeros((6, 6))

counter = 0
for i in range(6):
    for j in range(6):
        jarak[i][j] = data.iloc[counter]['Jarak']
        counter += 1

print(jarak)

[[0.   5.2  4.4  4.1  2.3  0.02]
 [5.3  0.   4.7  3.2  4.   5.3 ]
 [4.4  4.7  0.   4.8  4.2  2.8 ]
 [4.1  3.2  4.8  0.   2.2  4.1 ]
 [1.9  4.   4.2  2.2  0.   2.3 ]
 [0.02 5.3  2.8  4.1  2.   0.  ]]


In [148]:
n_data = data.copy()
n_data['Jarak'] = data['Jarak'].apply(lambda x: 1/(x*1000) if x > 0 else 0)
n_data
# Mencari attractiveness

Asal        Tujuan     Jarak  Waktu  KonfirmasiCovid
0      Puskesmas     Puskesmas  0.000000      0         0.000000
1      Puskesmas  SerdangWetan  0.000192     11         0.000000
2      Puskesmas      Palasari  0.000227     16         0.000000
3      Puskesmas     Rancagong  0.000244     11         0.000000
4      Puskesmas         Legok  0.000435      7         0.000000
5      Puskesmas       Babakan  0.050000      1         0.000000
6   SerdangWetan     Puskesmas  0.000189     11         0.000000
7   SerdangWetan  SerdangWetan  0.000000      0         0.000000
8   SerdangWetan      Palasari  0.000213     13         0.497059
9   SerdangWetan     Rancagong  0.000313      9         0.864706
10  SerdangWetan         Legok  0.000250     10         2.152941
11  SerdangWetan       Babakan  0.000189     11         1.082353
12      Palasari     Puskesmas  0.000227     16         0.000000
13      Palasari  SerdangWetan  0.000213     13         2.011834
14      Palasari      Palasari  0.000000      0         0.000000
15      Palasari     Rancagong  0.000208     14         1.739645
16      Palasari         Legok  0.000238     13         4.331361
17      Palasari       Babakan  0.000357     10         2.177515
18     Rancagong     Puskesmas  0.000244     11         0.000000
19     Rancagong  SerdangWetan  0.000313      9         1.156463
20     Rancagong      Palasari  0.000208     14         0.574830
21     Rancagong     Rancagong  0.000000      0         0.000000
22     Rancagong         Legok  0.000455      8         2.489796
23     Rancagong       Babakan  0.000244     11         1.251701
24         Legok     Puskesmas  0.000526      7         0.000000
25         Legok  SerdangWetan  0.000250      9         0.464481
26         Legok      Palasari  0.000238     15         0.230874
27         Legok     Rancagong  0.000455      8         0.401639
28         Legok         Legok  0.000000      0         0.000000
29         Legok       Babakan  0.000435      6         0.502732
30       Babakan     Puskesmas  0.050000      1         0.000000
31       Babakan  SerdangWetan  0.000189     11         0.923913
32       Babakan      Palasari  0.000357     10         0.459239
33       Babakan     Rancagong  0.000244     11         0.798913
34       Babakan         Legok  0.000500      8         1.989130
35       Babakan       Babakan  0.000000      0         0.000000

In [149]:
size_mapping = {
    'Puskesmas': 0,
    'SerdangWetan': 1,
    'Palasari': 2,
    'Rancagong': 3,
    'Legok': 4,
    'Babakan': 5
}
n_data['Asal'] = n_data['Asal'].map(size_mapping)
n_data['Tujuan'] = n_data['Tujuan'].map(size_mapping)
n_data

# Mapping data Asal dan an tujTanTujuan

Asal  Tujuan     Jarak  Waktu  KonfirmasiCovid
0      0       0  0.000000      0         0.000000
1      0       1  0.000192     11         0.000000
2      0       2  0.000227     16         0.000000
3      0       3  0.000244     11         0.000000
4      0       4  0.000435      7         0.000000
5      0       5  0.050000      1         0.000000
6      1       0  0.000189     11         0.000000
7      1       1  0.000000      0         0.000000
8      1       2  0.000213     13         0.497059
9      1       3  0.000313      9         0.864706
10     1       4  0.000250     10         2.152941
11     1       5  0.000189     11         1.082353
12     2       0  0.000227     16         0.000000
13     2       1  0.000213     13         2.011834
14     2       2  0.000000      0         0.000000
15     2       3  0.000208     14         1.739645
16     2       4  0.000238     13         4.331361
17     2       5  0.000357     10         2.177515
18     3       0  0.000244     11         0.000000
19     3       1  0.000313      9         1.156463
20     3       2  0.000208     14         0.574830
21     3       3  0.000000      0         0.000000
22     3       4  0.000455      8         2.489796
23     3       5  0.000244     11         1.251701
24     4       0  0.000526      7         0.000000
25     4       1  0.000250      9         0.464481
26     4       2  0.000238     15         0.230874
27     4       3  0.000455      8         0.401639
28     4       4  0.000000      0         0.000000
29     4       5  0.000435      6         0.502732
30     5       0  0.050000      1         0.000000
31     5       1  0.000189     11         0.923913
32     5       2  0.000357     10         0.459239
33     5       3  0.000244     11         0.798913
34     5       4  0.000500      8         1.989130
35     5       5  0.000000      0         0.000000

In [150]:
n_data['Pheromones'] = np.ones((36,1))
n_data
# Menginisialisasi pheromones

Asal  Tujuan     Jarak  Waktu  KonfirmasiCovid  Pheromones
0      0       0  0.000000      0         0.000000         1.0
1      0       1  0.000192     11         0.000000         1.0
2      0       2  0.000227     16         0.000000         1.0
3      0       3  0.000244     11         0.000000         1.0
4      0       4  0.000435      7         0.000000         1.0
5      0       5  0.050000      1         0.000000         1.0
6      1       0  0.000189     11         0.000000         1.0
7      1       1  0.000000      0         0.000000         1.0
8      1       2  0.000213     13         0.497059         1.0
9      1       3  0.000313      9         0.864706         1.0
10     1       4  0.000250     10         2.152941         1.0
11     1       5  0.000189     11         1.082353         1.0
12     2       0  0.000227     16         0.000000         1.0
13     2       1  0.000213     13         2.011834         1.0
14     2       2  0.000000      0         0.000000         1.0
15     2       3  0.000208     14         1.739645         1.0
16     2       4  0.000238     13         4.331361         1.0
17     2       5  0.000357     10         2.177515         1.0
18     3       0  0.000244     11         0.000000         1.0
19     3       1  0.000313      9         1.156463         1.0
20     3       2  0.000208     14         0.574830         1.0
21     3       3  0.000000      0         0.000000         1.0
22     3       4  0.000455      8         2.489796         1.0
23     3       5  0.000244     11         1.251701         1.0
24     4       0  0.000526      7         0.000000         1.0
25     4       1  0.000250      9         0.464481         1.0
26     4       2  0.000238     15         0.230874         1.0
27     4       3  0.000455      8         0.401639         1.0
28     4       4  0.000000      0         0.000000         1.0
29     4       5  0.000435      6         0.502732         1.0
30     5       0  0.050000      1         0.000000         1.0
31     5       1  0.000189     11         0.923913         1.0
32     5       2  0.000357     10         0.459239         1.0
33     5       3  0.000244     11         0.798913         1.0
34     5       4  0.000500      8         1.989130         1.0
35     5       5  0.000000      0         0.000000         1.0

In [151]:
attractiveness = np.zeros((6, 6))
waktu = np.zeros((6, 6))
covid = np.zeros((6, 6))

counter = 0
for i in range(6):
    for j in range(6):
        attractiveness[i][j] = n_data.iloc[counter]['Jarak']
        waktu[i][j] = n_data.iloc[counter]['Waktu']
        covid[i][j] = n_data.iloc[counter]['KonfirmasiCovid']
        counter += 1

pheromones = np.ones((6, 6))

print(attractiveness)
print(pheromones)
print(waktu)
print(covid)

# Menampilkan nilai attractiveness serta pheromones

[[0.         0.00019231 0.00022727 0.0002439  0.00043478 0.05      ]
 [0.00018868 0.         0.00021277 0.0003125  0.00025    0.00018868]
 [0.00022727 0.00021277 0.         0.00020833 0.0002381  0.00035714]
 [0.0002439  0.0003125  0.00020833 0.         0.00045455 0.0002439 ]
 [0.00052632 0.00025    0.0002381  0.00045455 0.         0.00043478]
 [0.05       0.00018868 0.00035714 0.0002439  0.0005     0.        ]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[ 0. 11. 16. 11.  7.  1.]
 [11.  0. 13.  9. 10. 11.]
 [16. 13.  0. 14. 13. 10.]
 [11.  9. 14.  0.  8. 11.]
 [ 7.  9. 15.  8.  0.  6.]
 [ 1. 11. 10. 11.  8.  0.]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.49705882 0.86470588 2.15294118 1.08235294]
 [0.         2.01183432 0.         1.73964497 4.33136095 2.17751479]
 [0.         1.15646259 0.57482993 0.         2.48979592 1.25170068]
 [0.         0.4644

In [152]:
def run_wpm(path):
    jaraks = np.array([])
    waktus = np.array([])
    covids = np.array([])
    for f in range(5): #Sesuai jumlah semut
        totalJarak = 0
        totalWaktu = 0
        totalCovid = 0
        for i in range(1, 6): #Calculate jarak, waktu, dan covid untuk setiap semut dari asal ke tujuan
            totalJarak = totalJarak + jarak[path[f][i-1]][path[f][i]]
            totalWaktu = totalWaktu + waktu[path[f][i-1]][path[f][i]]
            totalCovid = totalCovid + covid[path[f][i-1]][path[f][i]]
        if f == 0:
            jaraks = np.array([[totalJarak]])
            waktus = np.array([[totalWaktu]])
            covids = np.array([[totalCovid]])
        else:
            jaraks = np.append(jaraks, [[totalJarak]], axis=0)
            waktus = np.append(waktus, [[totalWaktu]], axis=0)
            covids = np.append(covids, [[totalCovid]], axis=0)
    path = np.append(path, jaraks, axis=1) #Kolom index  6
    path = np.append(path, waktus, axis=1) #Kolom index  7
    path = np.append(path, covids, axis=1) #Kolom index  8

    temp = path[:, 6].copy()
    
    #Masuk ke dalam WPM Utama

    #Tetapkan weight
    weight = np.array([3,1,2])
    weight = weight/np.sum(weight)
    
    path[:, 6] = np.amin(path[:, 6])/path[:, 6] #Jarak - Non Benefit
    path[:, 7] = np.amin(path[:, 7])/path[:, 7] #Waktu - Non benefit
    path[:, 8] = path[:, 8]/np.amax(path[:, 8]) #Covid - Benefit

    path[:, 6] = path[:, 6]**weight[0]
    path[:, 7] = path[:, 7]**weight[1]
    path[:, 8] = path[:, 8]**weight[2]

    sumPath = np.array([])
    for i in range(5):
        pro = 1
        for j in range(6, 9):
            pro = pro * path[i, j]
        sumPath = np.append(sumPath, [pro])
    path = np.append(path, np.transpose([sumPath]), axis=1)
    path = np.append(path, np.transpose([temp]), axis=1)
    return path

In [153]:
def run_aco(a, b, decay):
    for i in range(5): #Jumlah iterasi
        final_path = np.array([])
        for j in range(5): #Jumlah semut/ambulan
            chosen_path = np.array([0])
            for k in range(5):
                accP = np.array([[],[]])

                for l in range(6):
                    isContinue = False
                    for temp in chosen_path: #Ngecek ud pernah dilewatin ato blm path ny
                        if temp == l:
                            isContinue = True
                            break
                    if isContinue == True: #kalo ud dilewatin, iterasi loop di skip
                        continue
                    p = (pheromones[chosen_path[-1]][l]**a) * (attractiveness[chosen_path[-1]][l]**b)
                    print(f"{chosen_path[-1]} - {l} p: {p}")
                    accP = np.append(accP, np.array([[p],[l]]), axis=1)
                total = 0
                for p in accP[0]:
                    total = total + p
                
                for n in range(accP[0].size):
                    accP[0][n] = accP[0][n] / total
                
                for n in reversed(range(accP[0].size)):
                    for m in range(n):
                        accP[0][n] = accP[0][n] + accP[0][m]
                    
                i = random.Random().random()

                for n in range(accP[0].size):
                    if i <= accP[0][n]:
                        chosen_path = np.append(chosen_path, [int(accP[1][n])])
                        print("Chosen Path: ", chosen_path)
                        break
                print()
            
            final_path = [chosen_path] if j == 0 else np.append(final_path, [chosen_path], axis=0)
            
        wpm_result = run_wpm(final_path)
        print(wpm_result)

        #Update pheromones
        for i in range(6):
            for j in range(6):
                pheromones[i][j] = pheromones[i][j] - decay
                for ant in range(5):
                    for pointer in range(1, 6):
                        if wpm_result[ant][pointer] == j and wpm_result[ant][pointer-1] == i:
                            pheromones[i][j] = pheromones[i][j] - (1/wpm_result[ant][10])
        
        print(pheromones)
        if (pheromones < 0).any():
            finalIndex = np.argmax(wpm_result[:, 9])
            return wpm_result[finalIndex,[0,1,2,3,4,5]]

print("\nBest Path: ", run_aco(1, 1, 0.05))
    

0 - 1 p: 0.0001923076923076923
0 - 2 p: 0.00022727272727272727
0 - 3 p: 0.00024390243902439024
0 - 4 p: 0.0004347826086956522
0 - 5 p: 0.05
Chosen Path:  [0 5]

5 - 1 p: 0.00018867924528301886
5 - 2 p: 0.00035714285714285714
5 - 3 p: 0.00024390243902439024
5 - 4 p: 0.0005
Chosen Path:  [0 5 4]

4 - 1 p: 0.00025
4 - 2 p: 0.0002380952380952381
4 - 3 p: 0.00045454545454545455
Chosen Path:  [0 5 4 1]

1 - 2 p: 0.0002127659574468085
1 - 3 p: 0.0003125
Chosen Path:  [0 5 4 1 2]

2 - 3 p: 0.00020833333333333335
Chosen Path:  [0 5 4 1 2 3]

0 - 1 p: 0.0001923076923076923
0 - 2 p: 0.00022727272727272727
0 - 3 p: 0.00024390243902439024
0 - 4 p: 0.0004347826086956522
0 - 5 p: 0.05
Chosen Path:  [0 5]

5 - 1 p: 0.00018867924528301886
5 - 2 p: 0.00035714285714285714
5 - 3 p: 0.00024390243902439024
5 - 4 p: 0.0005
Chosen Path:  [0 5 2]

2 - 1 p: 0.0002127659574468085
2 - 3 p: 0.00020833333333333335
2 - 4 p: 0.0002380952380952381
Chosen Path:  [0 5 2 3]

3 - 1 p: 0.0003125
3 - 4 p: 0.0004545454545454

In [ ]:
import pandas as pd
result = pd.DataFrame()
for i in range(100):
    result[i] = run_aco(1, 1, 0.05)

result.to_csv("result.csv")