In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
import random
# Import library yang dibutuhkan

In [2]:
a = np.array([[1],[2]])
b = np.append(a, np.array([[1],[2]]), axis=1)
print(b)
c = np.append(b, [1,2])
print(c)

[[1 1]
 [2 2]]
[1 1 2 2 1 2]


In [3]:
data = pd.read_csv('./dataset.csv')
data
# Read data dalam bentuk csv

Asal        Tujuan  Jarak  Waktu  KonfirmasiCovid
0      Puskesmas     Puskesmas   0.00      0         0.000000
1      Puskesmas  SerdangWetan   5.20     11       340.000000
2      Puskesmas      Palasari   4.40     16       169.000000
3      Puskesmas     Rancagong   4.10     11       294.000000
4      Puskesmas         Legok   2.30      7       732.000000
5      Puskesmas       Babakan   0.02      1       368.000000
6   SerdangWetan     Puskesmas   5.30     11         0.000000
7   SerdangWetan  SerdangWetan   0.00      0         0.000000
8   SerdangWetan      Palasari   4.70     13         0.497059
9   SerdangWetan     Rancagong   3.20      9         0.864706
10  SerdangWetan         Legok   4.00     10         2.152941
11  SerdangWetan       Babakan   5.30     11         1.082353
12      Palasari     Puskesmas   4.40     16         0.000000
13      Palasari  SerdangWetan   4.70     13         2.011834
14      Palasari      Palasari   0.00      0         0.000000
15      Palasari     Rancagong   4.80     14         1.739645
16      Palasari         Legok   4.20     13         4.331361
17      Palasari       Babakan   2.80     10         2.177515
18     Rancagong     Puskesmas   4.10     11         0.000000
19     Rancagong  SerdangWetan   3.20      9         1.156463
20     Rancagong      Palasari   4.80     14         0.574830
21     Rancagong     Rancagong   0.00      0         0.000000
22     Rancagong         Legok   2.20      8         2.489796
23     Rancagong       Babakan   4.10     11         1.251701
24         Legok     Puskesmas   1.90      7         0.000000
25         Legok  SerdangWetan   4.00      9         0.464481
26         Legok      Palasari   4.20     15         0.230874
27         Legok     Rancagong   2.20      8         0.401639
28         Legok         Legok   0.00      0         0.000000
29         Legok       Babakan   2.30      6         0.502732
30       Babakan     Puskesmas   0.02      1         0.000000
31       Babakan  SerdangWetan   5.30     11         0.923913
32       Babakan      Palasari   2.80     10         0.459239
33       Babakan     Rancagong   4.10     11         0.798913
34       Babakan         Legok   2.00      8         1.989130
35       Babakan       Babakan   0.00      0         0.000000

In [4]:
data.isnull().sum()
# Menghitung jumlah data yang NULL

Asal               0
Tujuan             0
Jarak              0
Waktu              0
KonfirmasiCovid    0
dtype: int64

In [5]:
n_data = data
n_data['Jarak'] = data['Jarak'].apply(lambda x: x * 1000)
n_data['Jarak'] = data['Jarak'].apply(lambda x: 1/x if x > 0 else 0)
n_data
# Mencari attractiveness

Asal        Tujuan     Jarak  Waktu  KonfirmasiCovid
0      Puskesmas     Puskesmas  0.000000      0         0.000000
1      Puskesmas  SerdangWetan  0.000192     11       340.000000
2      Puskesmas      Palasari  0.000227     16       169.000000
3      Puskesmas     Rancagong  0.000244     11       294.000000
4      Puskesmas         Legok  0.000435      7       732.000000
5      Puskesmas       Babakan  0.050000      1       368.000000
6   SerdangWetan     Puskesmas  0.000189     11         0.000000
7   SerdangWetan  SerdangWetan  0.000000      0         0.000000
8   SerdangWetan      Palasari  0.000213     13         0.497059
9   SerdangWetan     Rancagong  0.000313      9         0.864706
10  SerdangWetan         Legok  0.000250     10         2.152941
11  SerdangWetan       Babakan  0.000189     11         1.082353
12      Palasari     Puskesmas  0.000227     16         0.000000
13      Palasari  SerdangWetan  0.000213     13         2.011834
14      Palasari      Palasari  0.000000      0         0.000000
15      Palasari     Rancagong  0.000208     14         1.739645
16      Palasari         Legok  0.000238     13         4.331361
17      Palasari       Babakan  0.000357     10         2.177515
18     Rancagong     Puskesmas  0.000244     11         0.000000
19     Rancagong  SerdangWetan  0.000313      9         1.156463
20     Rancagong      Palasari  0.000208     14         0.574830
21     Rancagong     Rancagong  0.000000      0         0.000000
22     Rancagong         Legok  0.000455      8         2.489796
23     Rancagong       Babakan  0.000244     11         1.251701
24         Legok     Puskesmas  0.000526      7         0.000000
25         Legok  SerdangWetan  0.000250      9         0.464481
26         Legok      Palasari  0.000238     15         0.230874
27         Legok     Rancagong  0.000455      8         0.401639
28         Legok         Legok  0.000000      0         0.000000
29         Legok       Babakan  0.000435      6         0.502732
30       Babakan     Puskesmas  0.050000      1         0.000000
31       Babakan  SerdangWetan  0.000189     11         0.923913
32       Babakan      Palasari  0.000357     10         0.459239
33       Babakan     Rancagong  0.000244     11         0.798913
34       Babakan         Legok  0.000500      8         1.989130
35       Babakan       Babakan  0.000000      0         0.000000

In [6]:
n_data['Pheromones'] = np.ones((36,1))
n_data
# Menginisialisasi pheromones

Asal        Tujuan     Jarak  Waktu  KonfirmasiCovid  Pheromones
0      Puskesmas     Puskesmas  0.000000      0         0.000000         1.0
1      Puskesmas  SerdangWetan  0.000192     11       340.000000         1.0
2      Puskesmas      Palasari  0.000227     16       169.000000         1.0
3      Puskesmas     Rancagong  0.000244     11       294.000000         1.0
4      Puskesmas         Legok  0.000435      7       732.000000         1.0
5      Puskesmas       Babakan  0.050000      1       368.000000         1.0
6   SerdangWetan     Puskesmas  0.000189     11         0.000000         1.0
7   SerdangWetan  SerdangWetan  0.000000      0         0.000000         1.0
8   SerdangWetan      Palasari  0.000213     13         0.497059         1.0
9   SerdangWetan     Rancagong  0.000313      9         0.864706         1.0
10  SerdangWetan         Legok  0.000250     10         2.152941         1.0
11  SerdangWetan       Babakan  0.000189     11         1.082353         1.0
12      Palasari     Puskesmas  0.000227     16         0.000000         1.0
13      Palasari  SerdangWetan  0.000213     13         2.011834         1.0
14      Palasari      Palasari  0.000000      0         0.000000         1.0
15      Palasari     Rancagong  0.000208     14         1.739645         1.0
16      Palasari         Legok  0.000238     13         4.331361         1.0
17      Palasari       Babakan  0.000357     10         2.177515         1.0
18     Rancagong     Puskesmas  0.000244     11         0.000000         1.0
19     Rancagong  SerdangWetan  0.000313      9         1.156463         1.0
20     Rancagong      Palasari  0.000208     14         0.574830         1.0
21     Rancagong     Rancagong  0.000000      0         0.000000         1.0
22     Rancagong         Legok  0.000455      8         2.489796         1.0
23     Rancagong       Babakan  0.000244     11         1.251701         1.0
24         Legok     Puskesmas  0.000526      7         0.000000         1.0
25         Legok  SerdangWetan  0.000250      9         0.464481         1.0
26         Legok      Palasari  0.000238     15         0.230874         1.0
27         Legok     Rancagong  0.000455      8         0.401639         1.0
28         Legok         Legok  0.000000      0         0.000000         1.0
29         Legok       Babakan  0.000435      6         0.502732         1.0
30       Babakan     Puskesmas  0.050000      1         0.000000         1.0
31       Babakan  SerdangWetan  0.000189     11         0.923913         1.0
32       Babakan      Palasari  0.000357     10         0.459239         1.0
33       Babakan     Rancagong  0.000244     11         0.798913         1.0
34       Babakan         Legok  0.000500      8         1.989130         1.0
35       Babakan       Babakan  0.000000      0         0.000000         1.0

In [7]:
size_mapping = {
    'Puskesmas': 0,
    'SerdangWetan': 1,
    'Palasari': 2,
    'Rancagong': 3,
    'Legok': 4,
    'Babakan': 5
}
n_data['Asal'] = n_data['Asal'].map(size_mapping)
n_data['Tujuan'] = n_data['Tujuan'].map(size_mapping)
n_data

# Mapping data Asal dan an tujTanTujuan

Asal  Tujuan     Jarak  Waktu  KonfirmasiCovid  Pheromones
0      0       0  0.000000      0         0.000000         1.0
1      0       1  0.000192     11       340.000000         1.0
2      0       2  0.000227     16       169.000000         1.0
3      0       3  0.000244     11       294.000000         1.0
4      0       4  0.000435      7       732.000000         1.0
5      0       5  0.050000      1       368.000000         1.0
6      1       0  0.000189     11         0.000000         1.0
7      1       1  0.000000      0         0.000000         1.0
8      1       2  0.000213     13         0.497059         1.0
9      1       3  0.000313      9         0.864706         1.0
10     1       4  0.000250     10         2.152941         1.0
11     1       5  0.000189     11         1.082353         1.0
12     2       0  0.000227     16         0.000000         1.0
13     2       1  0.000213     13         2.011834         1.0
14     2       2  0.000000      0         0.000000         1.0
15     2       3  0.000208     14         1.739645         1.0
16     2       4  0.000238     13         4.331361         1.0
17     2       5  0.000357     10         2.177515         1.0
18     3       0  0.000244     11         0.000000         1.0
19     3       1  0.000313      9         1.156463         1.0
20     3       2  0.000208     14         0.574830         1.0
21     3       3  0.000000      0         0.000000         1.0
22     3       4  0.000455      8         2.489796         1.0
23     3       5  0.000244     11         1.251701         1.0
24     4       0  0.000526      7         0.000000         1.0
25     4       1  0.000250      9         0.464481         1.0
26     4       2  0.000238     15         0.230874         1.0
27     4       3  0.000455      8         0.401639         1.0
28     4       4  0.000000      0         0.000000         1.0
29     4       5  0.000435      6         0.502732         1.0
30     5       0  0.050000      1         0.000000         1.0
31     5       1  0.000189     11         0.923913         1.0
32     5       2  0.000357     10         0.459239         1.0
33     5       3  0.000244     11         0.798913         1.0
34     5       4  0.000500      8         1.989130         1.0
35     5       5  0.000000      0         0.000000         1.0

In [8]:
from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# n_data['Jarak'] = pd.DataFrame(data=scaler.fit_transform(n_data['Jarak']), columns=n_data.columns)
# n_data['Jarak'] = StandardScaler().fit_transform(n_data['Jarak'], n_data.columns)
# n_data

# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import StandardScaler

# ct = ColumnTransformer([
#         ('somename', StandardScaler(), ['Jarak'])
#     ], remainder='passthrough')

# temp = ct.fit_transform(n_data)
# n_data = pd.DataFrame(data=temp)
# n_data

# scaled_features = n_data.copy()

# col_names = ['Jarak']
# features = scaled_features[col_names]
# scaler = StandardScaler().fit(features.values)
# features = scaler.transform(features.values)

# scaled_features[col_names] = features
# print(scaled_features)

# n_data = scaled_features

In [9]:
t_data = n_data
a = 1
b = 1
# Inisialisasi variabel

In [10]:
attractiveness = np.zeros((6, 6))

counter = 0
for r in range(6):
    for c in range(6):
        attractiveness[r][c] = t_data.iloc[counter]['Jarak']
        counter = counter + 1

pheromones = np.ones((6, 6))

print(attractiveness)
print(pheromones)

# Menampilkan nilai attractiveness serta pheromones

[[0.         0.00019231 0.00022727 0.0002439  0.00043478 0.05      ]
 [0.00018868 0.         0.00021277 0.0003125  0.00025    0.00018868]
 [0.00022727 0.00021277 0.         0.00020833 0.0002381  0.00035714]
 [0.0002439  0.0003125  0.00020833 0.         0.00045455 0.0002439 ]
 [0.00052632 0.00025    0.0002381  0.00045455 0.         0.00043478]
 [0.05       0.00018868 0.00035714 0.0002439  0.0005     0.        ]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [11]:
def run_aco():
    for i in range(5): #Jumlah iterasi
        # print(f"i = {i}")
        final_path = np.array([[]])
        for j in range(2): #Jumlah semut/ambulan
            # print(f"j = {j}")
            chosen_path = np.array([0])
            for k in range(5):
                # print(f"k = {k}")
                accP = np.array([[],[]])

                for l in range(6):
                    # print(f"l = {l}")
                    isContinue = False
                    for temp in chosen_path: #Ngecek ud pernah dilewatin ato blm path ny
                        if temp == l:
                            isContinue = True
                            break
                    if isContinue == True: #kalo ud dilewatin, iterasi loop di skip
                        # print("Skip")
                        continue
                    p = (pheromones[chosen_path[-1]][l]**a) * (attractiveness[chosen_path[-1]][l]**b)
                    print(f"{chosen_path[-1]} - {l} p: {p}")
                    accP = np.append(accP, np.array([[p],[l]]), axis=1)
                total = 0
                for p in accP[0]:
                    total += p
                
                for n in range(accP[0].size):
                    accP[0][n] = accP[0][n] / total
                
                # print("\nSebelum akumulasi: ", accP[0], "/iteration")

                for n in reversed(range(accP[0].size)):
                    for m in range(n):
                        accP[0][n] = accP[0][n] + accP[0][m]
                    
                r = random.Random().random()

                # print("\nSesudah akumulasi: ", r, " - ", accP, "\n")

                for n in range(accP[0].size):
                    if r <= accP[0][n]:
                        chosen_path = np.append(chosen_path, [int(accP[1][n])])
                        print("Chosen Path: ", chosen_path)
                        break
                print()
        final_path = np.append(final_path, [chosen_path])
        return final_path.astype(int)

print(run_aco())
    

0 - 1 p: 0.0001923076923076923
0 - 2 p: 0.00022727272727272727
0 - 3 p: 0.00024390243902439024
0 - 4 p: 0.0004347826086956522
0 - 5 p: 0.05
Chosen Path:  [0 5]

5 - 1 p: 0.00018867924528301886
5 - 2 p: 0.00035714285714285714
5 - 3 p: 0.00024390243902439024
5 - 4 p: 0.0005
Chosen Path:  [0 5 1]

1 - 2 p: 0.0002127659574468085
1 - 3 p: 0.0003125
1 - 4 p: 0.00025
Chosen Path:  [0 5 1 4]

4 - 2 p: 0.0002380952380952381
4 - 3 p: 0.00045454545454545455
Chosen Path:  [0 5 1 4 3]

3 - 2 p: 0.00020833333333333335
Chosen Path:  [0 5 1 4 3 2]

0 - 1 p: 0.0001923076923076923
0 - 2 p: 0.00022727272727272727
0 - 3 p: 0.00024390243902439024
0 - 4 p: 0.0004347826086956522
0 - 5 p: 0.05
Chosen Path:  [0 5]

5 - 1 p: 0.00018867924528301886
5 - 2 p: 0.00035714285714285714
5 - 3 p: 0.00024390243902439024
5 - 4 p: 0.0005
Chosen Path:  [0 5 4]

4 - 1 p: 0.00025
4 - 2 p: 0.0002380952380952381
4 - 3 p: 0.00045454545454545455
Chosen Path:  [0 5 4 2]

2 - 1 p: 0.0002127659574468085
2 - 3 p: 0.000208333333333333

In [12]:
def run_aco():
    for i in range(5): #Jumlah iterasi
        final_path = np.array([[]])
        for j in range(2): #Jumlah semut
            chosen_path = np.array([0])
            for k in range(5):
                accP = np.array([[],[]])

                for l in range(6):
                    if l in chosen_path: #Memeriksa apakah sudah dilewati atau belum
                        continue
                    p = (pheromones[chosen_path[-1]][l]**a) * (attractiveness[chosen_path[-1]][l]**b)
                    print(f"{chosen_path[-1]} - {l} p: {p}")
                    accP = np.append(accP, np.array([[p],[l]]), axis=1)
                total = 0
                for p in accP[0]:
                    total += p
                
                for n in range(accP[0].size):
                    accP[0][n] = accP[0][n] / total
                
                for n in reversed(range(accP[0].size)):
                    for m in range(n):
                        accP[0][n] = accP[0][n] + accP[0][m]
                    
                r = random.Random().random()
                for n in range(accP[0].size):
                    if r <= accP[0][n]:
                        chosen_path = np.append(chosen_path, [int(accP[1][n])])
                        print("Chosen Path:", chosen_path)
                        break
                print()
        final_path = np.append(final_path, [chosen_path])
        return final_path.astype(int)

print(run_aco())
    

0 - 1 p: 0.0001923076923076923
0 - 2 p: 0.00022727272727272727
0 - 3 p: 0.00024390243902439024
0 - 4 p: 0.0004347826086956522
0 - 5 p: 0.05
Chosen Path: [0 5]

5 - 1 p: 0.00018867924528301886
5 - 2 p: 0.00035714285714285714
5 - 3 p: 0.00024390243902439024
5 - 4 p: 0.0005
Chosen Path: [0 5 1]

1 - 2 p: 0.0002127659574468085
1 - 3 p: 0.0003125
1 - 4 p: 0.00025
Chosen Path: [0 5 1 2]

2 - 3 p: 0.00020833333333333335
2 - 4 p: 0.0002380952380952381
Chosen Path: [0 5 1 2 4]

4 - 3 p: 0.00045454545454545455
Chosen Path: [0 5 1 2 4 3]

0 - 1 p: 0.0001923076923076923
0 - 2 p: 0.00022727272727272727
0 - 3 p: 0.00024390243902439024
0 - 4 p: 0.0004347826086956522
0 - 5 p: 0.05
Chosen Path: [0 5]

5 - 1 p: 0.00018867924528301886
5 - 2 p: 0.00035714285714285714
5 - 3 p: 0.00024390243902439024
5 - 4 p: 0.0005
Chosen Path: [0 5 2]

2 - 1 p: 0.0002127659574468085
2 - 3 p: 0.00020833333333333335
2 - 4 p: 0.0002380952380952381
Chosen Path: [0 5 2 1]

1 - 3 p: 0.0003125
1 - 4 p: 0.00025
Chosen Path: [0 5 

In [13]:
# def aco(data, a, b, ant, iteration, decay = 0.05):
#     # create an ant colonization optimization algorithm with n iterations
#     # a and b are the pheromone and distance parameters
#     # data is a pandas dataframe with columns 'Asal', 'Tujuan', 'Jarak'
#     # returns a list of the best path found
#     data['Jarak'] = data['Jarak'].apply(lambda x: 1/x if x > 0 else 0)
#     # initialize pheromones
#     data['Pheromones'] = np.ones((6, 6))
#     # map the data
#     size_mapping = {
#         'Puskesmas': 0,
#         'SerdangWetan': 1,
#         'Palasari': 2,
#         'Rancagong': 3,
#         'Legok': 4,
#         'Babakan': 5
#     }
#     data['Asal'] = data['Asal'].map(size_mapping)
#     data['Tujuan'] = data['Tujuan'].map(size_mapping)
#     # scale the data
#     scaled_features = data.copy()
#     col_names = ['Jarak']
#     features = scaled_features[col_names]
#     scaler = StandardScaler().fit(features.values)
#     features = scaler.transform(features.values)
#     scaled_features[col_names] = features

#     visibility = np.zeros((6, 6))
#     counter = 0
#     for r in range(6):
#         for c in range(6):
#             visibility[r][c] = t_data.iloc[counter]['Jarak']
#             counter = counter + 1

#     for i in range(iteration): #Jumlah iterasi
#         chosen_path = np.ndarray(ant, [0])
#         for j in range(6): #Jumlah kota
#             p = np.zeros((ant, 6))
#             for k in range(ant): #Jumlah semut
#                 if j in chosen_path[k]:
#                     continue
#                 p = (data['Pheromones'][chosen_path[k][-1]][j]**a) * (data['Jarak'][chosen_path[k][-1]][j]**b)
          
        
#         # update pheromones
#         for j in range(36):
#             data['Pheromones'][j] -= decay

# aco(data, 1, 1, 2, 5)